blank_lines_upper_bound = 0
brace_style = "AlwaysNextLine"
combine_control_expr = false
control_brace_style = "AlwaysNextLine"
enum_discrim_align_threshold = 20
fn_params_layout = "Vertical"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
imports_layout = "Vertical"
indent_style = "Visual"
max_width = 80
merge_derives = false
merge_imports = true
newline_style = "Unix"
reorder_impl_items = true
reorder_imports = false
reorder_modules = false
struct_field_align_threshold = 20
unstable_features = true
wrap_comments = true